parse_mode = "Markdown"
lang = {
    "error_to_user": "Произошла ошибка на сервере.",
    "error_to_log": "слышработать, там ошибки летят:\n`{}`",
    "not_admin": "Ты не админ.",
    "admin_error": "Ты админ, соре",
    "enabled": "Включено",
    "disabled": "Отключено",
    "on_start": "sup\nДоступные команды ты можешь посмотреть командой /help",
    "help_header": "Список команд:",
    "success": "Удачно",
    "failed": "Провал",
    "roulette_start": "Запущена русская рулетка, {} на прицеле",
    "roulette_failed": "1tap, {}",
    "roulette_success": "Missed to {} due to spread",
    "rate_list": ['норм', 'годно', 'говно', 'такое'],
    "coin_list": ['Орел', 'Решка'],
    "random_header": "Твое сгенерированное число -> `{}`",
    "added_to_chat": "sup\nДоступные команды ты можешь посмотреть командой /help",
    "passgen_header": "Твой сгенерированный пароль -> `{}`",
    "id": "`{}` ID - `{}`",
    "chatid_chat": "`{}` ID - `{}`",
    "chatid_pm": "Your ID - `{}`",
    "info_text": "Бота разработал @es3n1n\nСо списком всех команд ты можешь ознакомится командой /help\n09.11.18",
    "status_text": "Status: `Alive`\nЦП: `{}%`\nОЗУ: `{}%`\nUptime: {}\nБота разработал @es3n1n\nСо списком всех команд ты можешь ознакомится командой /help\n09.11.18",
    "uptime_year": "`{}` год(а), ",
    "uptime_month": "`{}` месяц(ев), ",
    "uptime_day": "`{}` дня(ей), ",
    "uptime_hour": "`{}` час(а), ",
    "uptime_min": "`{}` минут(ы), ",
    "uptime_sec": "`{}` секунд(ы)",
    "weather_error": "Error\nВозможно данный город отсутствует в базе",
    "weather_text": "Погода в {}\nТемпература: {}°C\nСкорость ветра: {}m/s\nВлажность: {}%",
    "answer_dont_understand": "Я вас не понимаю",
    "answer_no_short_answers": "Нет доступных ответов",
    "wiki_answer": "*{}*\n\n`{}...`\n\n[Подробнее]({})",
    "wiki_not_found": "`Not_Found`",
    "choice_answer": "Я выбираю *{}*.",
    "choice_error_same_args": "Параметры для выбора одинаковые",
    "choice_error_arguments": "Для команды нужно передать все аргументы",
    "setleft_success": "Успешно.",
    "setwelcome_success": "Успешно.",
    "setrules_success": "Успешно.",
    "del_error_arguments": "Для удаления сообщения нужен реплай на сообщение, которое нужно удалить.",
    "brainfuck_imp_res": "Code:\n`{}`\n\nOutput:\n`{}`",
    "brainfuck_enc_res":"Text:\n`{}`\n\nOutput:\n`{}`",
    "bug_sent": "Отправлено.",
    "bug_log": "New #bug from user `{}`:\n`{}`",
    "pong": "Pong.",
    "ping": "Ping.",
    "shrug": "¯\_(ツ)_ /¯",
    "mute_error_args": "Ошибка. Недостаточно параметров для мута.",
    "mute_accept_button_text": "Да",
    "mute_accept_text": "Вы серьезно хотите замутить {} ?",
    "mute_accepted": "Отправили в мут работягу",
    "mute_decline_button_text": "Отмена",
    "mute_declined_text": "Отменено.",
    "mute_error_same_users": "Ошибка. Запрещено мутить себя.",
    "mute_error_parsing": "Ошибка парсинга значений",
    "mute_error_bot": "Ошибка. Я не могу себя замутить",
    "unmute_accept_button_text": "Да.",
    "unmute_accept_text": "Вы серьезно хотите снять огр. с {} ?",
    "unmute_accepted": "Готово",
    "unmute_decline_button_text": "Отмена",
    "unmute_declined_text": "Отменено.",
    "unmute_error_bot": "Ошибка. Я не могу себя размутить",
    "unmute_error_args": "Ошибка. Недостаточно параметров для снятия ограничений.",
    "ban_accept_button_text": "Да.",
    "ban_accept_text": "Вы серьезно хотите забанить {} ?",
    "ban_accepted": "Готово",
    "ban_decline_button_text": "Отмена",
    "ban_declined_text": "Отменено.",
    "ban_error_bot": "Ошибка. Я не могу себя забанить",
    "ban_error_args": "Ошибка. Недостаточно параметров для бана.",
    "kick_accept_button_text": "Да.",
    "kick_accept_text": "Вы серьезно хотите кикнуть {} ?",
    "kick_accepted": "Готово",
    "kick_decline_button_text": "Отмена",
    "kick_declined_text": "Отменено.",
    "kick_error_bot": "Ошибка. Я не могу себя кикнуть",
    "kick_error_args": "Ошибка. Недостаточно параметров для кика.",
    "log_rebooted_message": "Перезагрузилось",
    "kickme_accept_button_text": "Ебош",
    "kickme_decline_button_text": "Вырубай",
    "kickme_accept_text": "Серьезно?",
    "banme_accept_button_text": "Ебош",
    "banme_decline_button_text": "Вырубай",
    "banme_accept_text": "rly?",
    "muteme_error_parsing": "Ошибка парсинга значений",
    "muteme_accept_button_text": "Ебош",
    "muteme_decline_button_text": "Вырубай",
    "muteme_accept_text": "вна2ре?",
    "ignore_added": "Added",
    "ignore_removed": "Removed",
    "ping_answer_with_host": "Pong?\nServer: `{}`\nConnection: `{}ms`",
    "ping_timed_out": "Timed out.",
    "update_error_perms": "У тебя нет прав на это действие",
    "update_started": "Обновление началось, в лог будет отправлен бекап бд с минуты на минуту",
    "backup_databases_msg_log": "Backup of databases has been created before updating"
#    "ping_answer_with_host": "Pong!\nConnection to `{}` - `{}`",
}